spring.application.name=json-inventory-service
spring.datasource.url=${DB_URL_INVENTORY}
spring.datasource.username=${DB_USER_INVENTORY}
spring.datasource.password=${DB_PASS_INVENTORY}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
app.frontend.url=${FRONTEND_URL:http://localhost:5173,http://localhost:3000}
app.jwt.secret=${JWT_SECRET}
server.port=8083